config/routes.rb
Rails.application.routes.draw do
  root to: 'epicks#index'

  resources :epicks do
    post :update_status, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/epick.rb
class Epick < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'kacper' && password == 'Qwerty1@'
    end
  end
end

app/controllers/epicks_controller.rb
class EpicksController < ApplicationController
  before_action :set_epick, only: %i[ show edit update destroy update_status]

  # GET /epicks or /epicks.json
  def index
    Epick.all.where("updated_at < ?", Date.today).update_all(status: false)
    @epicks = Epick.all.order(:created_at)
  end

  # GET /epicks/1 or /epicks/1.json
  def show
  end

  # GET /epicks/new
  def new
    @epick = Epick.new
  end

  # GET /epicks/1/edit
  def edit
  end

  # POST /epicks or /epicks.json
  def create
    @epick = Epick.new(epick_params)

    respond_to do |format|
      if @epick.save
        format.html { redirect_to @epick, notice: "Epick was successfully created." }
        format.json { render :show, status: :created, location: @epick }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @epick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epicks/1 or /epicks/1.json
  def update
    respond_to do |format|
      if @epick.update(epick_params)
        format.html { redirect_to @epick, notice: "Epick was successfully updated." }
        format.json { render :show, status: :ok, location: @epick }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @epick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epicks/1 or /epicks/1.json
  def destroy
    @epick.destroy
    respond_to do |format|
      format.html { redirect_to epicks_url, notice: "Epick was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_status
    Epick.all.where("updated_at < ?", Date.today).update_all(status: false)
    @epick.update(status: !@epick.status)
    @epicks = Epick.all.order(:created_at)
    
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epick
      @epick = Epick.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def epick_params
      params.require(:epick).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicks_helper.rb
module EpicksHelper
end

app/views/epicks/_form.html.erb
<%= form_with(model: epick) do |form| %>
  <% if epick.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% epick.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/epicks/edit.html.erb
<h1>Editing Epick</h1>

<%= render 'form', epick: @epick %>

<%= link_to 'Show', @epick %> |
<%= link_to 'Back', epicks_path %>

app/views/epicks/index.html.erb
<% @epicks.each_slice(4) do |epicks| %>
  <div class="row">
    <% epicks.each do |epick| %>
      <div class="three columns">
        <%= button_to epick.name, update_status_epick_path(epick), class: (epick.status? ? 'button-green' : 'button-red') %>
      </div>
    <% end %>
  </div>
<% end %>

<%= link_to '^', new_epick_path %>

app/views/epicks/new.html.erb
<h1>New Epick</h1>

<%= render 'form', epick: @epick %>

<%= link_to 'Back', epicks_path %>

app/views/epicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @epick.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @epick.status %>
</p>

<%= link_to 'Edit', edit_epick_path(@epick) %> |
<%= link_to 'Back', epicks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Organizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="icon" type="image/png" href="favicon.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="padding-top: 17%">
        <%= yield %>
    </div>
  </body>
</html>